From owner-Zip-Bugs@LISTS.WKU.EDU Tue Mar 02 23:38:00 1999
Return-Path: <owner-Zip-Bugs@LISTS.WKU.EDU>
Delivered-To: roelofs@sonic.net
Received: (qmail 32017 invoked from network); 2 Mar 1999 23:37:59 -0000
Received: from growl.pobox.com (208.210.124.27)
  by buzz.sonic.net with SMTP; 2 Mar 1999 23:37:59 -0000
Received: by growl.pobox.com (Postfix, from userid 15)
	id 0D703665F; Tue,  2 Mar 1999 18:37:43 -0500 (EST)
Received: from axp1.wku.edu (axp1.wku.edu [161.6.18.1])
	by growl.pobox.com (Postfix) with ESMTP
	id D23716533; Tue,  2 Mar 1999 18:37:13 -0500 (EST)
X-ListName: Zip/UnZip Bug Reports <Zip-Bugs@LISTS.WKU.EDU>
Message-ID: <000001be650d$97e99340$4ba535c3@->
Reply-To: Zip-Bugs@LISTS.WKU.EDU,
	"Jorge Serrano" <mvisual@programando.com>
From: "Jorge Serrano" <mvisual@programando.com>
To: <Zip-Bugs@lists.wku.edu>
Subject: UnZip ActiveX Ocx
Date: Mon, 1 Mar 1999 21:20:02 -0000
MIME-Version: 1.0
Content-Type: multipart/mixed;
              boundary="----=_NextPart_000_0004_01BE6429.44C43A60"
Sender: owner-Zip-Bugs@LISTS.WKU.EDU
Status: RO

This is a multi-part message in MIME format.

------=_NextPart_000_0004_01BE6429.44C43A60
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

Hi Greg,

sorry by my English.

I am a Spanish student and I am very interesting with Info-ZIP.

I'm the Mundo Visual - Visual Basic webmaster. Is a Spanish Visual Basic
site.

If you want, I can to put your Info-Zip files on my web-server. I am the
webmaster of that server too.

Furthermore, I have developed an ActiveX Ocx with VB5.

This ActiveX Ocx needs the UnZip.DLL library and the VB5 (SP3) runtimes.

It's very simple and easy to use.

Is my contribution to your job and the other people.

I hope that early my control support compress too. At the moment the
MVZipUnzip control support Unzip.


Thanks in advanced.

Regards.

Jorge Serrano.
mvisual@programando.com
Mundo Visual - Visual Basic
http://www.programando.com/visualbasic/mundovisual/



------=_NextPart_000_0004_01BE6429.44C43A60
Content-Type: application/octet-stream;
	name="MVZipUnzip.zip"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="MVZipUnzip.zip"

------=_NextPart_000_0004_01BE6429.44C43A60--



